version: "3"


services:
    flask:
        container_name: flask_con
        build: .
        ports:
         - "5000:5000"
        depends_on:
         - db
        networks:
         - inside_net
        volumes:
         - .:/src
    web:
        container_name: web_con
        build:
          context: ./js
          dockerfile: Dockerfile
        ports:
         - "8000:80"
        volumes:
         - .:/src
        networks:
         - inside_net
    db:
        image: mariadb
        container_name: db_con
        environment:
         - MYSQL_ROOT_PASSWORD=password
         - MYSQL_DATABASE=relations
         - MYSQL_USER=user
         - MYSQL_PASSWORD=password
        ports:
         - "3306:3306"
        volumes:
         - ./mariadb_data:/var/lib/mysql
         - ./dumps:/docker-entrypoint-initdb.d
        networks:
         - inside_net

networks:
  inside_net:
    driver: bridge
    ipam:
      driver: default
